theme: jekyll-theme-minimal
description: I'm a second year PhD student in Control and Dynamical Systems (CDS) at Caltech, and I'm advised by Professor Richard Murray. My research is on Formal Methods for Test and Evaluation (T&E) and Verification and Validation (V&V) of Autonomous Systems.
